/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assig2;
import java.io.File;
import java.util.Arrays;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.ListBranchCommand;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.api.errors.InvalidRemoteException;
import org.eclipse.jgit.api.errors.TransportException;
import org.eclipse.jgit.lib.Ref;

public class App {
    public static void main(String[] args) {
        try {
            model.cloneRepo("https://github.com/arnbaeck/assig2", "testing11");
        }catch (InvalidRemoteException e){
            e.printStackTrace();
        }catch (GitAPIException e){
            e.printStackTrace();
        }


    }


}
