/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assig2;
import java.io.File;
import java.util.Arrays;

import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.ListBranchCommand;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.api.errors.InvalidRemoteException;
import org.eclipse.jgit.api.errors.TransportException;
import org.eclipse.jgit.lib.Ref;


public class App {
    public static void main(String[] args) throws InvalidRemoteException, TransportException, GitAPIException {
       Git r = Git.cloneRepository()
                .setURI("https://github.com/arnbaeck/assig2")
                //.setDirectory(new File("")) return status info, "clone failed because uri is not valid"
                .setBranchesToClone(Arrays.asList("refs/heads/main"))
                //.setNoCheckout(true)
                .call();

        for (Ref f : r.branchList().setListMode(ListBranchCommand.ListMode.ALL).call())
            System.out.println("found branch " + f.getName());

    }


}
